"""Standing places within 20 miles of Livingston.

Coordinates are the venue, not the town centre. The radius check in tests
drops anything that drifts outside 20 miles. Seasons are inclusive months.
Prices are reminders, not a quote — the email tells you to check the site.
"""

from planner.model import Activity

FREE = "Free to enter."
TICKET = "Ticketed — check the site for current prices and times."


def _place(**kwargs: object) -> Activity:
    data = {
        "kind": "standing",
        "when": "Open most weekends",
        "season": None,
    }
    data.update(kwargs)
    return Activity(**data)  # type: ignore[arg-type]


CATALOGUE: tuple[Activity, ...] = (
    _place(
        name="Almondell and Calderwood Country Park",
        summary="River paths, a play area and the iron bridge between Broxburn and East Calder. Long enough for both of them, with places to picnic if it stays dry.",
        url="https://www.westlothian.gov.uk/almondell-and-calderwood",
        lat=55.9020,
        lon=-3.4830,
        price="free",
        audience="family",
        setting="outdoor",
        category="outdoors",
        price_note=FREE,
        area="Broxburn",
    ),
    _place(
        name="Beecraigs Country Park",
        summary="Loch, red deer and woodland above Linlithgow. Walk the park together, or let them loose on the trails while you do the shorter loop.",
        url="https://www.westlothian.gov.uk/beecraigs",
        lat=55.9618,
        lon=-3.5295,
        price="free",
        audience="family",
        setting="outdoor",
        category="outdoors",
        price_note=FREE + " Car parking charges can apply.",
        area="Linlithgow",
    ),
    _place(
        name="Beecraigs bike trails",
        summary="Waymarked trails in the same park. A proper ride for this age — you can cycle with them or wait at the visitor centre.",
        url="https://www.westlothian.gov.uk/beecraigs",
        lat=55.9618,
        lon=-3.5295,
        price="free",
        audience="kids",
        setting="outdoor",
        category="sport",
        price_note=FREE + " Bikes are not hired here; bring your own.",
        area="Linlithgow",
    ),
    _place(
        name="Polkemmet Country Park",
        summary="Woodland, a golf course to walk past, and open ground at Whitburn. Easy half-day if you do not want to drive into Edinburgh.",
        url="https://www.westlothian.gov.uk/polkemmet",
        lat=55.8522,
        lon=-3.6895,
        price="free",
        audience="family",
        setting="outdoor",
        category="outdoors",
        price_note=FREE,
        area="Whitburn",
    ),
    _place(
        name="Muiravonside Country Park",
        summary="Quiet park between Linlithgow and Falkirk, with the river and old farm buildings. Good when the busier parks feel crowded.",
        url="https://www.falkirkleisureandculture.org/venues/muiravonside-country-park/",
        lat=55.9705,
        lon=-3.6550,
        price="free",
        audience="family",
        setting="outdoor",
        category="outdoors",
        price_note=FREE,
        area="Whitecross",
    ),
    _place(
        name="Linlithgow Loch and the Peel",
        summary="Lap the loch under the palace. Flat, and long enough that an 11-year-old and a 13-year-old will actually feel they have been somewhere.",
        url="https://www.historicenvironment.scot/visit-a-place/places/linlithgow-palace/",
        lat=55.9780,
        lon=-3.5980,
        price="free",
        audience="family",
        setting="outdoor",
        category="outdoors",
        price_note="The loch path is free. The palace itself is ticketed.",
        area="Linlithgow",
    ),
    _place(
        name="Union Canal towpath",
        summary="Level path from Livingston towards Linlithgow or Winchburgh. Bikes, scooters or a straight walk, with no hills to negotiate.",
        url="https://www.scottishcanals.co.uk/visit/canals/visit-the-union-canal",
        lat=55.8825,
        lon=-3.5480,
        price="free",
        audience="family",
        setting="outdoor",
        category="outdoors",
        price_note=FREE,
        area="Livingston",
    ),
    _place(
        name="Livingston Skatepark",
        summary="The concrete park in Almondvale Park, the 1981 bowl that is now a listed structure. Free session for anyone who skates, scooters or rides a BMX. You can watch from the side.",
        url="https://www.google.com/maps/search/?api=1&query=Livingston+Skatepark+Almondvale+Park",
        lat=55.8810,
        lon=-3.5160,
        price="free",
        audience="kids",
        setting="outdoor",
        category="sport",
        price_note=FREE,
        area="Livingston",
    ),
    _place(
        name="Eliburn Park",
        summary="Reservoir loop plus the adventure play area in north Livingston. The play kit still suits the 11-year-old; the 13-year-old usually prefers the path.",
        url="https://www.westlothian.gov.uk/article/34238/Eliburn-Park",
        lat=55.9030,
        lon=-3.5450,
        price="free",
        audience="kids",
        setting="outdoor",
        category="outdoors",
        price_note=FREE + " Fishing on the reservoir is a separate permit.",
        area="Livingston",
    ),
    _place(
        name="National Museum of Scotland",
        summary="Dolly the sheep, the Grand Gallery, and enough floors that they can split up and meet you. The best free wet-weather day in reach of Livingston.",
        url="https://www.nms.ac.uk/national-museum-of-scotland",
        lat=55.9470,
        lon=-3.1908,
        price="free",
        audience="family",
        setting="indoor",
        category="museum",
        price_note=FREE + " Some special exhibitions are ticketed.",
        area="Edinburgh",
    ),
    _place(
        name="Scottish National Gallery",
        summary="The gallery on the Mound. Short enough not to drag, and free. Pair it with the museum if you are already in town.",
        url="https://www.nationalgalleries.org/visit/scottish-national-gallery",
        lat=55.9509,
        lon=-3.1956,
        price="free",
        audience="family",
        setting="indoor",
        category="museum",
        price_note=FREE,
        area="Edinburgh",
    ),
    _place(
        name="Scottish National Portrait Gallery",
        summary="Queen Street. The building is half the visit, and it is a dry, central stop that is not another country park.",
        url="https://www.nationalgalleries.org/visit/scottish-national-portrait-gallery",
        lat=55.9555,
        lon=-3.1934,
        price="free",
        audience="family",
        setting="indoor",
        category="museum",
        price_note=FREE,
        area="Edinburgh",
    ),
    _place(
        name="National Gallery of Modern Art (Modern One)",
        summary="Modern art in a house in the west of the city, with grounds outside if the rain stops. Easier to park than the Old Town.",
        url="https://www.nationalgalleries.org/visit/scottish-national-gallery-modern-art",
        lat=55.9508,
        lon=-3.2276,
        price="free",
        audience="family",
        setting="indoor",
        category="museum",
        price_note=FREE,
        area="Edinburgh",
    ),
    _place(
        name="Museum of Childhood",
        summary="Royal Mile museum of toys and games. A bit nostalgic for you, still a proper indoor hour for them, and free.",
        url="https://www.edinburghmuseums.org.uk/venue/museum-childhood",
        lat=55.9506,
        lon=-3.1855,
        price="free",
        audience="family",
        setting="indoor",
        category="museum",
        price_note=FREE,
        area="Edinburgh",
    ),
    _place(
        name="Royal Botanic Garden Edinburgh",
        summary="Large gardens in Inverleith. Glasshouses are a paid extra; the garden itself is free and an easy wander.",
        url="https://www.rbge.org.uk/",
        lat=55.9650,
        lon=-3.2098,
        price="free",
        audience="family",
        setting="outdoor",
        category="outdoors",
        price_note="Garden free. Glasshouses are ticketed.",
        area="Edinburgh",
    ),
    _place(
        name="Holyrood Park and Arthur's Seat",
        summary="The climb above the parliament. This age can do the top if you pick a clear path and turn back in wind or low cloud.",
        url="https://www.historicenvironment.scot/visit-a-place/places/holyrood-park/",
        lat=55.9444,
        lon=-3.1600,
        price="free",
        audience="family",
        setting="outdoor",
        category="outdoors",
        price_note=FREE,
        area="Edinburgh",
    ),
    _place(
        name="Harlaw and Threipmuir, Pentland Hills",
        summary="Reservoirs at the north end of the Pentlands, the closest real hill walk to Livingston. Boots if it has been wet.",
        url="https://www.pentlandhills.org/",
        lat=55.8700,
        lon=-3.2830,
        price="free",
        audience="family",
        setting="outdoor",
        category="outdoors",
        price_note=FREE,
        area="Balerno",
    ),
    _place(
        name="South Queensferry and the Forth Bridges",
        summary="The three bridges from the Hawes Pier side, plus the high street. A short walk with a proper view, not a hike.",
        url="https://www.theforthbridges.org/",
        lat=55.9918,
        lon=-3.3875,
        price="free",
        audience="family",
        setting="outdoor",
        category="outdoors",
        price_note=FREE,
        area="South Queensferry",
    ),
    _place(
        name="The Kelpies",
        summary="The horse-head sculptures at Helix Park. Walking round them is free; the inside tour is a separate ticket if you want it.",
        url="https://www.thekelpies.co.uk/",
        lat=56.0195,
        lon=-3.7555,
        price="free",
        audience="family",
        setting="outdoor",
        category="outdoors",
        price_note="The park is free. Guided tours inside a Kelpie are ticketed.",
        area="Falkirk",
    ),
    _place(
        name="Cammo Estate",
        summary="Ruined house and woods on the west edge of Edinburgh. Quieter than Holyrood, and an easy add-on if you are already over that way.",
        url="https://www.edinburgh.gov.uk/directory/10250/cammo-estate-local-nature-reserve",
        lat=55.9605,
        lon=-3.3205,
        price="free",
        audience="family",
        setting="outdoor",
        category="outdoors",
        price_note=FREE,
        area="Edinburgh",
    ),
    _place(
        name="Cramond foreshore",
        summary="The causeway to Cramond Island is only there around low tide. If the tide is wrong, the shore path still works. Check the tide before you promise the island.",
        url="https://www.edinburgh.gov.uk/directory/10255/cramond-foreshore",
        lat=55.9790,
        lon=-3.3008,
        price="free",
        audience="family",
        setting="outdoor",
        category="outdoors",
        price_note=FREE,
        area="Edinburgh",
    ),
    _place(
        name="Callendar Park",
        summary="Big park in Falkirk with Callendar House in the middle. The grounds are the free part; check the house separately if you want indoors.",
        url="https://www.falkirkleisureandculture.org/venues/callendar-park/",
        lat=55.9945,
        lon=-3.7675,
        price="free",
        audience="family",
        setting="outdoor",
        category="outdoors",
        price_note=FREE + " House entry may be charged.",
        area="Falkirk",
    ),
    _place(
        name="Dedridge Ponds",
        summary="Short nature trail and play park a few minutes from The Centre. Useful when you want an hour outside, not a day trip.",
        url="https://www.visitwestlothian.co.uk/things-to-do/country-parks-play-parks/dedridge-ponds/",
        lat=55.8730,
        lon=-3.5220,
        price="free",
        audience="family",
        setting="outdoor",
        category="outdoors",
        price_note=FREE,
        area="Livingston",
    ),
    _place(
        name="Bellsquarry Wood",
        summary="Woodland on the south side of Livingston, on the Shale Trail. A local walk that still feels like a proper outing.",
        url="https://www.google.com/maps/search/?api=1&query=Bellsquarry+Wood+Livingston",
        lat=55.8690,
        lon=-3.5480,
        price="free",
        audience="family",
        setting="outdoor",
        category="outdoors",
        price_note=FREE,
        area="Livingston",
    ),
    _place(
        name="Blackford Hill",
        summary="Steep enough to count as a climb, with the city and the Pentlands from the top. Shorter than Arthur's Seat.",
        url="https://www.edinburgh.gov.uk/directory/10248/blackford-hill",
        lat=55.9245,
        lon=-3.1948,
        price="free",
        audience="family",
        setting="outdoor",
        category="outdoors",
        price_note=FREE,
        area="Edinburgh",
    ),
    _place(
        name="Almond Valley Heritage Centre",
        summary="Farm animals, the shale-oil museum, play areas and a narrow-gauge train, on the edge of Livingston. Built for a family day rather than a quick look.",
        url="https://www.almondvalley.co.uk/",
        lat=55.8890,
        lon=-3.5495,
        price="paid",
        audience="family",
        setting="either",
        category="farm",
        price_note="About £13 adult and £11 child (2–15), as published by the centre. Closed 25–26 Dec and 1–2 Jan.",
        area="Livingston",
    ),
    _place(
        name="Five Sisters Zoo",
        summary="West Calder zoo with a wide collection, mostly outside, plus a reptile house if you need a break from the weather. Give it a few hours.",
        url="https://fivesisterszoo.co.uk/our-zoo/opening-times-prices/",
        lat=55.8468,
        lon=-3.5695,
        price="paid",
        audience="family",
        setting="outdoor",
        category="animals",
        price_note="About £21.95 adult and £16.50 child (3–15). Soft play is a separate ticket and is aimed younger.",
        area="West Calder",
    ),
    _place(
        name="Edinburgh Zoo",
        summary="The big zoo at Corstorphine, including the penguins and the hill. Mostly outdoors, so pick it on the drier day.",
        url="https://www.edinburghzoo.org.uk/",
        lat=55.9424,
        lon=-3.2680,
        price="paid",
        audience="family",
        setting="outdoor",
        category="animals",
        price_note=TICKET,
        area="Edinburgh",
    ),
    _place(
        name="Dynamic Earth",
        summary="Planetarium, earthquake and the indoor Earth story at Holyrood. A full wet-weather afternoon for this age.",
        url="https://dynamicearth.org.uk/",
        lat=55.9504,
        lon=-3.1745,
        price="paid",
        audience="family",
        setting="indoor",
        category="science",
        price_note=TICKET,
        area="Edinburgh",
    ),
    _place(
        name="Deep Sea World",
        summary="Aquarium under the Forth Bridge at North Queensferry. Almost all indoors, and the tunnel usually lands well with both of them.",
        url="https://www.deepseaworld.com/",
        lat=56.0086,
        lon=-3.3940,
        price="paid",
        audience="family",
        setting="indoor",
        category="animals",
        price_note=TICKET,
        area="North Queensferry",
    ),
    _place(
        name="Edinburgh Castle",
        summary="The castle rock, the great hall and the views. A lot of it is outside on the ramparts, so it is a poor choice in driving rain.",
        url="https://www.edinburghcastle.scot/",
        lat=55.9486,
        lon=-3.1999,
        price="paid",
        audience="family",
        setting="outdoor",
        category="history",
        price_note=TICKET,
        area="Edinburgh",
    ),
    _place(
        name="Linlithgow Palace",
        summary="The roofless palace by the loch. History they can climb around, close to home. Exposed if the weather turns.",
        url="https://www.historicenvironment.scot/visit-a-place/places/linlithgow-palace/",
        lat=55.9784,
        lon=-3.6012,
        price="paid",
        audience="family",
        setting="outdoor",
        category="history",
        price_note=TICKET,
        area="Linlithgow",
    ),
    _place(
        name="Blackness Castle",
        summary="The ship-shaped castle on the Forth. Smaller than Edinburgh Castle and usually quieter. The courtyard is open to the weather.",
        url="https://www.historicenvironment.scot/visit-a-place/places/blackness-castle/",
        lat=56.0063,
        lon=-3.5158,
        price="paid",
        audience="family",
        setting="outdoor",
        category="history",
        price_note=TICKET,
        area="Blackness",
    ),
    _place(
        name="Hopetoun House",
        summary="The big house and grounds west of South Queensferry. House rooms if it rains, parkland if it does not.",
        url="https://hopetoun.co.uk/",
        lat=55.9954,
        lon=-3.4628,
        price="paid",
        audience="family",
        setting="either",
        category="history",
        price_note=TICKET,
        area="South Queensferry",
    ),
    _place(
        name="House of the Binns",
        summary="NTS house above the Forth near Abercorn, with a roof walk when it is open. A smaller history stop than the castle.",
        url="https://www.nts.org.uk/visit/places/house-of-the-binns",
        lat=55.9890,
        lon=-3.5260,
        price="paid",
        audience="family",
        setting="either",
        category="history",
        season=(4, 10),
        when="Usually open April to October",
        price_note=TICKET + " Season is typically April to October.",
        area="Abercorn",
    ),
    _place(
        name="Falkirk Wheel",
        summary="The boat lift. The trip through the wheel is the part worth paying for; watching it from the side is shorter.",
        url="https://www.scottishcanals.co.uk/visit/canals/visit-the-forth-clyde-canal/attractions/the-falkirk-wheel",
        lat=56.0003,
        lon=-3.8412,
        price="paid",
        audience="family",
        setting="either",
        category="history",
        price_note=TICKET + " Boat trips are timed — book ahead at the weekend.",
        area="Falkirk",
    ),
    _place(
        name="Jupiter Artland",
        summary="Sculpture park in the grounds at Wilkieston, a few minutes from Livingston. Outdoors, and only in its open season.",
        url="https://www.jupiterartland.org/",
        lat=55.9058,
        lon=-3.4172,
        price="paid",
        audience="family",
        setting="outdoor",
        category="outdoors",
        season=(5, 9),
        when="Usually open May to September",
        price_note=TICKET + " Closed over winter.",
        area="Wilkieston",
    ),
    _place(
        name="Conifox Adventure Park",
        summary="Outdoor adventure park at Kirkliston — trails and play big enough for 11 and 13. The indoor soft play on the same site is aimed younger (up to 12).",
        url="https://www.conifox.co.uk/tickets-prices/",
        lat=55.9648,
        lon=-3.3705,
        price="paid",
        audience="family",
        setting="outdoor",
        category="adventure",
        season=(3, 10),
        when="Outdoor park, roughly March to October",
        price_note="Outdoor park about £6.50 adult and £9.50 child at weekends. Book online.",
        area="Kirkliston",
    ),
    _place(
        name="Go Ape, Dalkeith Country Park",
        summary="High ropes in the trees at Dalkeith. Height rules apply, and this age can usually do the main course if they clear the minimum. You can go on with them or stay on the ground.",
        url="https://goape.co.uk/locations/dalkeith/",
        lat=55.8990,
        lon=-3.0700,
        price="paid",
        audience="kids",
        setting="outdoor",
        category="adventure",
        price_note="From about £21 a person. Check height rules before you book.",
        area="Dalkeith",
    ),
    _place(
        name="Camera Obscura and World of Illusions",
        summary="Mirror maze and hands-on illusions at the top of the Royal Mile. Indoors, and built for them to mess about in.",
        url="https://www.camera-obscura.co.uk/",
        lat=55.9489,
        lon=-3.1958,
        price="paid",
        audience="family",
        setting="indoor",
        category="science",
        price_note=TICKET,
        area="Edinburgh",
    ),
    _place(
        name="The Real Mary King's Close",
        summary="Guided tour under the Royal Mile. Spooky rather than gory, and a good indoor hour if they like a story.",
        url="https://www.realmarykingsclose.com/",
        lat=55.9498,
        lon=-3.1905,
        price="paid",
        audience="family",
        setting="indoor",
        category="history",
        price_note=TICKET,
        area="Edinburgh",
    ),
    _place(
        name="Edinburgh Dungeon",
        summary="Actor-led, gory, and played for laughs. Fine for this age if they like spooky shows. Skip it if they do not.",
        url="https://www.thedungeons.com/edinburgh/",
        lat=55.9510,
        lon=-3.1880,
        price="paid",
        audience="family",
        setting="indoor",
        category="show",
        price_note=TICKET,
        area="Edinburgh",
    ),
    _place(
        name="Vue, Edinburgh Omni Centre",
        summary="Cinema at the top of Leith Walk. Pick whatever is on that you are all willing to sit through. Easy wet-weather fallback.",
        url="https://www.myvue.com/cinema/edinburgh-omni-centre/whats-on",
        lat=55.9570,
        lon=-3.1860,
        price="paid",
        audience="family",
        setting="indoor",
        category="show",
        price_note=TICKET,
        area="Edinburgh",
    ),
    _place(
        name="EICA Ratho climbing",
        summary="Europe's largest indoor climbing arena, at Ratho. Book a taster or Clip 'n Climb. You can climb too, or wait with a coffee. The soft play on site is for younger children.",
        url="https://www.edinburghleisure.co.uk/venues/edinburgh-international-climbing-arena/",
        lat=55.9214,
        lon=-3.3938,
        price="paid",
        audience="kids",
        setting="indoor",
        category="sport",
        price_note=TICKET,
        area="Ratho",
    ),
    _place(
        name="Xcite public swimming",
        summary="Public swim for all ages. The nearest pools to Livingston are Bathgate, Linlithgow, Whitburn and Winchburgh. You can swim with them or watch from the side.",
        url="https://www.xcite.scot/activities/swimming/",
        lat=55.9024,
        lon=-3.6380,
        price="paid",
        audience="kids",
        setting="indoor",
        category="sport",
        price_note="About £6.60 adult, £4.50 under 18, or £19.45 for two adults and two under-18s. There is no pool at Xcite Livingston itself.",
        area="Bathgate",
    ),
)
